export const GET_ALL_CHOICES = "GET_ALL_CHOICES";
export const GET_CHOICES_BY_LETTER = "GET_CHOICES_BY_LETTER";
export const GET_PARENT_CHOICES = "GET_PARENT_CHOICES";
export const ADD_IF_COMMON_CHOICE = "ADD_IF_COMMON_CHOICE";

export const GET_PARENT_A_CHOICES = "GET_PARENT_A_CHOICES";
export const ADD_PARENT_A_CHOICE = "ADD_PARENT_A_CHOICE";
export const REMOVE_PARENT_A_CHOICE = "REMOVE_PARENT_A_CHOICE";
export const CLEAR_ALL_PARENT_A_CHOICES = "CLEAR_ALL_PARENT_A_CHOICES";

export const GET_PARENT_B_CHOICES = "GET_PARENT_B_CHOICES";
export const ADD_PARENT_B_CHOICE = "ADD_PARENT_B_CHOICE";
export const REMOVE_PARENT_B_CHOICE = "REMOVE_PARENT_B_CHOICE";
export const CLEAR_ALL_PARENT_B_CHOICES = "CLEAR_ALL_PARENT_B_CHOICES";

export const CLEAR_ALL_PARENT_CHOICES = "CLEAR_ALL_PARENT_CHOICES";
