export const GET_ALL_CHOICES = 'GET_ALL_CHOICES';
export const GET_ALL_COMBINATION_IDEAS = 'GET_ALL_COMBINATION_IDEAS';

export const ADD_IF_COMMON_CHOICE = 'ADD_IF_COMMON_CHOICE';
export const ADD_PARENT_A_CHOICE = 'ADD_PARENT_A_CHOICE';
export const ADD_PARENT_B_CHOICE = 'ADD_PARENT_B_CHOICE';