export const GET_PARENT_A_NAME = 'GET_PARENT_A_NAME';
export const SET_PARENT_A_NAME = 'SET_PARENT_A_NAME';
export const GET_PARENT_B_NAME = 'GET_PARENT_B_NAME';
export const SET_PARENT_B_NAME = 'SET_PARENT_B_NAME';